image: ebiwd/alpine-ssh

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # project specific variables can be defined here
  SSH_OWNER_ID: wd_drupl
  SSH_APACHE_ID: w3_wd01
  # set secrets in Settings -> Pipelines -> Secret Variables
  SSH_WD_DRUPL: secret-key
  SSH_W3_WD01: secret-key
before_script:
  - add-ssh-key ${SSH_OWNER_ID} "${SSH_WD_DRUPL}" $SSH_APACHE_ID "${SSH_W3_WD01}"
  - add-search-domain ebi.ac.uk
  - cd ${CI_PROJECT_DIR};

stages:
  - backup
  - build
  - deploy

backup-dev:
  stage: backup
  image: ebiwd/docker-drush:3.6
  tags:
    - docker
  script:
    - bin/dump sql dev
  artifacts:
    paths:
      - _sqldump
  only:
    - master

backup-stage:
  stage: backup
  image: ebiwd/docker-drush:3.6
  tags:
    - docker
  script:
    - bin/dump sql stage
  artifacts:
    paths:
      - _sqldump
  only:
    - master

backup-prod:
  stage: backup
  image: ebiwd/docker-drush:3.6
  tags:
    - docker
  script:
    - bin/dump sql prod
  artifacts:
    paths:
      - _sqldump
  only:
    - tags

build:
  stage: build
  image: ebiwd/docker-drush:3.6
  tags:
    - docker
  script:
    - composer install
    - cp ./custom_scripts/.htaccess dist/ # Required for Wordpress subfolder path installation
    - cp -r ./sis-game dist/
    - cp -r ./advanced-custom-fields-pro dist/wp-content/plugins/
  artifacts:
    expire_in: 1d
    paths:
      - dist/

deploy-dev:
  stage: deploy
  tags:
    - docker
  dependencies:
    - build
  script:
    - bin/deploy dev
    - for VM in ${EBI8_DEV_VMS}; do ssh -tt ${SSH_OWNER_ID}@${VM} 'ln -s /var/www/drupal/scienceinschool.org/_files/languages /var/www/drupal/scienceinschool.org/dist/wp-content/languages';  done;
  only:
    - master

deploy-stage:
  stage: deploy
  tags:
    - docker
  dependencies:
    - build
  script:
    - bin/deploy stage
    - for VM in ${EBI8_STAGE_VMS}; do ssh -tt ${SSH_OWNER_ID}@${VM} 'ln -s /var/www/drupal/scienceinschool.org/_files/languages /var/www/drupal/scienceinschool.org/dist/wp-content/languages';  done;
  only:
    - master

deploy-prod:
  stage: deploy
  tags:
    - docker
  dependencies:
    - build
  script:
    - bin/deploy prod
    - for VM in ${EBI8_PROD_VMS}; do ssh -tt ${SSH_OWNER_ID}@${VM} 'ln -s /var/www/drupal/scienceinschool.org/_files/languages /var/www/drupal/scienceinschool.org/dist/wp-content/languages';  done;
  only:
    - tags
